volumes:
  etc_wireguard:


services:
  wg-easy:
    environment:
      - LANG=de
      - WG_HOST=${HOSTNAME}
      - PASSWORD_HASH=${WG_PASSWORD_HASH}
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - WG_DEFAULT_DNS=8.8.8.8
      - WG_ALLOWED_IPS=0.0.0.0/0, ::/0
    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - etc_wireguard:/etc/wireguard
    ports:
      - "51820:51820/udp"
    #  - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      default: null
      proxy: null
    #labels:
    #  traefik.docker.network: proxy
    #  traefik.enable: "true"
    #  traefik.http.routers.wireguard-secure.entrypoints: websecure
    #  traefik.http.routers.wireguard-secure.middlewares: default@file
    #  traefik.http.routers.wireguard-secure.rule: Host(`wireguard.${HOSTNAME}`)
    #  traefik.http.routers.wireguard-secure.service: wireguard
    #  traefik.http.routers.wireguard-secure.tls: "true"
    #  traefik.http.routers.wireguard-secure.tls.certresolver: tls_resolver
    #  traefik.http.routers.wireguard.entrypoints: web
    #  traefik.http.routers.wireguard.rule: Host(`wireguard.${HOSTNAME}`)
    #  traefik.http.services.wireguard.loadbalancer.server.port: "51821"

networks:
  default:
  proxy:
    external: true
