services:
  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    command: --transaction-isolation=READ-COMMITTED --innodb_read_only_compressed=OFF
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/containers/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NEXTCLOUD_MYSQL_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_MYSQL_DATABASE}
      - MYSQL_USER=${NEXTCLOUD_MYSQL_USER}
      - MYSQL_INITDB_SKIP_TZINFO=1
      - MARIADB_AUTO_UPGRADE=1
    networks:
      default: null
  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    hostname: nextcloud-redis
    networks:
      default: null
    restart: unless-stopped
    command: redis-server --requirepass ${NEXTCLOUD_REDIS_PASSWORD}
  nextcloud-app:
    image: nextcloud:latest
    container_name: nextcloud-app
    restart: unless-stopped
    depends_on:
      - nextcloud-db
      - nextcloud-redis
    environment:
      TRUSTED_PROXIES: 172.16.255.254/16
      OVERWRITEPROTOCOL: https
      OVERWRITECLIURL: https://cloud.${HOSTNAME}
      OVERWRITEHOST: cloud.${HOSTNAME}
      REDIS_HOST: nextcloud-redis
      REDIS_HOST_PASSWORD: ${NEXTCLOUD_REDIS_PASSWORD}
    volumes:
      - ./app:/var/www/html
      - ./data:/var/www/html/data
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.nextcloud-secure.entrypoints: websecure
      traefik.http.routers.nextcloud-secure.middlewares: default@file
      traefik.http.routers.nextcloud-secure.rule: Host(`cloud.${HOSTNAME}`)
      traefik.http.routers.nextcloud-secure.service: nextcloud
      traefik.http.routers.nextcloud-secure.tls: "true"
      traefik.http.routers.nextcloud-secure.tls.certresolver: tls_resolver
      traefik.http.routers.nextcloud.entrypoints: web
      traefik.http.routers.nextcloud.rule: Host(`cloud.${HOSTNAME}`)
      traefik.http.services.nextcloud.loadbalancer.server.port: "80"
    networks:
      default: null
      proxy: null
networks:
  default:
  proxy:
    external: true
