services:
  frontend:
    container_name: personal-webpage
    build: .
    ports:
      - "3000:3000"
    labels:
      traefik.docker.network: proxy
      traefik.enable: "true"
      traefik.http.routers.frontend-secure.entrypoints: websecure
      traefik.http.routers.frontend-secure.middlewares: default@file
      traefik.http.routers.frontend-secure.rule: Host(`${HOSTNAME}`) || Host(`www.${HOSTNAME}`)
      traefik.http.routers.frontend-secure.service: frontend
      traefik.http.routers.frontend-secure.tls: "true"
      traefik.http.routers.frontend-secure.tls.certresolver: tls_resolver
      traefik.http.routers.frontend.entrypoints: web
      traefik.http.routers.frontend.rule: Host(`${HOSTNAME}`) || Host(`www.${HOSTNAME}`)
      traefik.http.services.frontend.loadbalancer.server.port: "3000"
    networks:
      default: null
      proxy: null
    restart: unless-stopped

networks:
  default:
  proxy:
    external: true
