version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_website
    volumes:
      - ~/personal_webpage:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=http"
      - "traefik.http.routers.nginx.rule=Host(`www.${HOSTNAME}`, `${HOSTNAME}`)"
      - "traefik.http.routers.nginx-secure.entrypoints=https"
      - "traefik.http.routers.nginx-secure.rule=Host(`www.${HOSTNAME}`, `${HOSTNAME}`)"
      - "traefik.http.routers.nginx-secure.tls=true"
      - "traefik.http.routers.nginx-secure.tls.certresolver=http"
      - "traefik.http.services.pnginx.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    restart: unless-stopped

networks:
  proxy:
    external: true
